### ISSUE TITLE
Edifice support

### ISSUE THREAD

**Issue by j-rivero** [ignition-tooling/release-tools#421]
This ticket tracks Edifice support for various platforms.

* See all supported platforms for Edifice on [this page](https://ignitionrobotics.org/docs/edifice).
* See the definition of Ignition's support categories on [this page](https://ignitionrobotics.org/docs/all/releases).

---

Operating System | Architecture | Packaging | CI | Functionality
---------------- | ------------ | --------- | -- | -------------
Ubuntu Bionic    | amd64        | ✅ Yes    | ✅ Yes, every pull request | ✅ All
.                | i386         | ✅ Yes    | No | ✅ All
.                | arm64        | ❓ Maybe  | No | Most low-level libraries known to work
.                | armhf        | ❓ Maybe  | No | Most low-level libraries known to work, DART physics engine not available
Ubuntu Focal     | amd64        | ✅ Yes    | ✅ Yes, every pull request | ✅ All
.                | arm64        | ❓ Maybe  | No | Most low-level libraries known to work
.                | armhf        | ❓ Maybe  | No | Most low-level libraries known to work, DART physics engine not available
Debian Buster    | amd64, i386, arm64, armhf | ❓ Maybe | No | Several libraries known to work
MacOS Catalina and BigSur | -   | ✅ Yes    | ✅ Yes, every pull request (TODO: which version?) | Ignition only works in headless mode (GUI does not render; instead of using `ign gazebo fuel.sdf` command, use `ign gazebo -s fuel.sdf` to start the server only).
Windows 10       | .            | ❓ Maybe  | ✅ Yes, every pull request | Command line utilities are not supported. All packages up to but not including `ign-gazebo` are currently building. DART physics engine is not supported. Qt (GUI functionality) is not supported.

---

There are some problems affecting different platforms in Edfice:

**Legend** :green_circle: in the repo :yellow_circle: waiting in the buildfarm :red_circle: requires action :black_circle: no release

### Linux

 * **Ubuntu amd64 platforms:**
   * :green_circle: Focal/amd64
   * :green_circle: Bionic/amd64

 * **Ubuntu i386 platforms:**
   *  :red_circle:  Bionic/i386: see https://github.com/ignitionrobotics/ign-physics/issues/248
   
 * **Ubuntu ARM platforms:**
   * :green_circle: Focal/arm64
   * :green_circle: Bionic/arm64

   * Focal/armhf:
     * :red_circle: rendering [linking problem with multiple definitions](https://build.osrfoundation.org/job/ign-rendering5-debbuilder/282/consoleFull#12775081966ea37b8d-a6d4-40ae-8431-d90c018842af)

   * Bionic/armhf:
     * Not support (previous work: [missing dart packages from PPA are not in the repo](https://build.osrfoundation.org/job/ign-physics3-debbuilder/129/consoleFull#5247017446e2e1b04-6601-495c-8fb8-66d94e1f3e63))

 * **Debian i386 platforms:**
    * :red_circle: rendering [No ogre-2.1 package](https://build.osrfoundation.org/job/ign-rendering5-debbuilder/278/consoleFull#2535498096e2e1b04-6601-495c-8fb8-66d94e1f3e63)
    * :red_circle: physics4 [No dartsim package](https://build.osrfoundation.org/job/ign-physics4-debbuilder/296/consoleFull#3494841816e2e1b04-6601-495c-8fb8-66d94e1f3e63)

 * **Debian amd64 platforms:**
   *  :green_circle: Buster/amd64
   * Sid/*:
     * Not supported. Need to check conflicts with current libraries there

 * **Debian ARM platforms:**
   * Buster/arm64
       * :red_circle:  Missing libdart

   *  Buster/armhf (raspbian)
       * :red_circle: [common4 tests need patching](https://build.osrfoundation.org/job/ign-common4-debbuilder/291/consoleFull#19419928336ea37b8d-a6d4-40ae-8431-d90c018842af)

### MacOSX

* **Brew**
  * :green_circle: Bottles

### Windows
* **From source**
  * The whole stack up to ign-gazebo5 should compile in a colcon-workspace. [ign-launch is still being ported.](https://github.com/ignitionrobotics/ign-launch/issues/89)
* **Conda-forge** (community effort)

**Comment by scpeters** [comment]
the focal armhf builds of sdformat11 are failing to identify the compiler

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat11-debbuilder&build=197)](https://build.osrfoundation.org/job/sdformat11-debbuilder/197/) https://build.osrfoundation.org/job/sdformat11-debbuilder/197/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=sdformat11-debbuilder&build=198)](https://build.osrfoundation.org/job/sdformat11-debbuilder/198/) https://build.osrfoundation.org/job/sdformat11-debbuilder/198/

~~~
dh_auto_configure -- \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
	cd obj-arm-linux-gnueabihf && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_AUTOGEN_VERBOSE=ON -DCMAKE_INSTALL_LIBDIR=lib/arm-linux-gnueabihf -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
CMake Error at /usr/share/cmake-3.16/Modules/CMakeCompilerIdDetection.cmake:26 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:211 (compiler_id_detection)
  /usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:230 (CMAKE_DETERMINE_COMPILER_ID_WRITE)
  /usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:32 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.16/Modules/CMakeDetermineCCompiler.cmake:116 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:23 (project)


CMake Error at /usr/share/cmake-3.16/Modules/CMakeCompilerIdDetection.cmake:26 (list):
  list sub-command REMOVE_ITEM requires two or more arguments.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:211 (compiler_id_detection)
  /usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:230 (CMAKE_DETERMINE_COMPILER_ID_WRITE)
  /usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:32 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/share/cmake-3.16/Modules/CMakeDetermineCCompiler.cmake:116 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:23 (project)
...
-- The C compiler identification is unknown
...
-- The CXX compiler identification is unknown
...
~~~

those cmake errors seem to match https://gitlab.kitware.com/cmake/cmake/-/issues/20568, which was allegedly fixed in https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5258, possibly in cmake 3.19.0?

I don't know why this doesn't affect the ignition debbuild jobs. The [ignition debbuild script](https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/docker/multidistribution-ignition-debbuild.bash#L10) sets `NEED_C11_COMPILER`, while the [debbuild script used by sdformat](https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/docker/multidistribution-debbuild.bash) does not, but the job itself sets `NEED_C17_COMPILER`, so I'm not sure what is going on.

**Comment by chapulina** [comment]
Edifice is EOL 🏁 🔥  🏢
